# Generated by Django 4.2.7 on 2023-11-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='next_element_name',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='prew_element_name',
        ),
    ]
