# Generated by Django 4.2.7 on 2023-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_guide_next_element_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='next_element_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='prew_element_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
