# Generated by Django 4.2.7 on 2023-11-21 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_guide_next_element_name_guide_prew_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
