# Generated by Django 4.2.7 on 2023-11-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_conversation_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmessage',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='botmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
