# Generated by Django 4.2.7 on 2023-11-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_botmessage_options_botmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='botmessage',
            options={'ordering': ('-time',)},
        ),
        migrations.RenameField(
            model_name='botmessage',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
