# Generated by Django 4.2.7 on 2023-12-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_email_profile_is_finished_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor')], default='Doctor', max_length=255),
        ),
    ]
