# Generated by Django 4.2.7 on 2023-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Full_name',
            field=models.CharField(default='Іванов Іван Іванович', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
