# Generated by Django 4.2.7 on 2023-12-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_full_name_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
